export const useCarouselBrands = () => [
  {
    imageUrl: "/logo-DAM.svg",
    alt: "",
    width: 250,
    height: 250,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/logo-goma.svg",
    alt: "",
    width: 250,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/logo-casa-angular.svg",
    alt: "",
    width: 300,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/logo-DAM.svg",
    alt: "",
    width: 250,
    height: 250,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/logo-goma.svg",
    alt: "",
    width: 250,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/logo-casa-angular.svg",
    alt: "",
    width: 300,
    height: 100,
    text: "",
    textSize: "",
  },
];
